/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package edu.handong.csee.isel.clami_;


public class Runner {

	public static void main(String[] args) {
		Runner runner = new Runner();
		runner.run(args);
	}
	
	private void run(String[] args) {
		DataCluster dataCluster = new DataCluster();
		Labeler labeler = new Labeler();
		MetricSelector metricSelector = new MetricSelector();
		InstanceSelector instanceSelector = new InstanceSelector();
		DatasetTester datasetTester = new DatasetTester();
		
		//DataCluster class
		 //복잡도를 2차원배열로 생성한다.
		dataCluster.setComplexity();
		
		//Labeler class
		 //instance를 metric value higher than median의 개수(=k) 별로 그룹화한다.
		labeler.groupInstances();
		 //위에서 그룹화된 instance를 또다시 두개의 그룹으로 나눈다. k를 기준으로 top half와 bottom half로 나눈다. Label bug or clean, a top half is bug label while a bottom half is clear label.
		labeler.labelInstance();
		
		//MetricSelector class
		 //violation과 mvs를 구한 뒤, metric selection을 한다.
		metricSelector.selectMetric();
		 //metric selection이 진행된 후 다시 결함예측을 위한 metric 복잡도의 2차원 array를 생성한다.
		metricSelector.setMetricSelectedComplexity();
		
		//InstanceSelector class
		 //violation을 구한 뒤, instance selection을 한다.
		instanceSelector.selectInstance();
		 //instance selection이 진행된 후 다시 결함예측을 위한 metric 복잡도의 2차원 array를 생성한다.
		instanceSelector.setInstanceSelectedComplexity();
		
		//DatasetTester class
		 //unlabed dataset에 metric selection을 적용해 test dataset을 생성한다.
		datasetTester.generateTestDataset();
		datasetTester.test();
	}
}


